/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.core.gui.controls;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.beans.BeanProperty;
import javax.swing.Icon;

/**
 *
 * @author TiMMy
 */
public class AccordionPanel extends javax.swing.JPanel {

    private boolean expanded = true;
    Dimension collapsedSize;
    
    public AccordionPanel() {
        initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(getBackground());
        g.fillRect(this.getWidth()-25, 0, 20, 20);
        Icon icon = expanded ? flatTreeExpandedIcon : flatTreeCollapsedIcon;
        icon.paintIcon(this, g, this.getWidth()-20, 10);
    }
    
    @Override
    protected void paintChildren(Graphics g) {
        if (expanded) {
            super.paintChildren(g);
        } else {
            //Don't paint children if collapsed
        }
    }
    
    public boolean getExpanded() {
        return expanded;
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "Is this panel expanded or collapsed.")
    public void setExpanded(boolean expanded) {
        this.expanded = expanded;
        Dimension size = getSize();
        if (size.width == 0 && size.height == 0) {
            return; //Not initialised
        } else if (collapsedSize == null) {
            collapsedSize = new Dimension(size.width, 25);
        }
        revalidate();
    }
    
    @Override
    public Dimension getPreferredSize() {
        if (expanded || collapsedSize == null) {
            return super.getPreferredSize();
        } else {
            return collapsedSize;
        }
    }
    
    @Override
    public Dimension getMaximumSize() {
        if (expanded || collapsedSize == null) {
            return super.getMaximumSize();
        } else {
            return collapsedSize;
        }
    }
    
    @Override
    public Dimension getMinimumSize() {
        if (expanded || collapsedSize == null) {
            return super.getMinimumSize();
        } else {
            return collapsedSize;
        }
    }
    
    @Override
    public Dimension getSize() {
        if (expanded || collapsedSize == null) {
            return super.getSize();
        } else {
            return collapsedSize;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flatTreeCollapsedIcon = new com.formdev.flatlaf.icons.FlatTreeCollapsedIcon();
        flatTreeExpandedIcon = new com.formdev.flatlaf.icons.FlatTreeExpandedIcon();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Click me to collapse"));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Point click = evt.getPoint();
        if (click.y < 20) {
            setExpanded(!expanded);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.formdev.flatlaf.icons.FlatTreeCollapsedIcon flatTreeCollapsedIcon;
    private com.formdev.flatlaf.icons.FlatTreeExpandedIcon flatTreeExpandedIcon;
    // End of variables declaration//GEN-END:variables
}
