/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.core.gui.controls;

import com.sfc.sf2.helpers.PathHelpers;
import java.beans.BeanProperty;
import java.io.File;
import java.nio.file.Path;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JTextField;

/**
 *
 * @author TiMMy
 */
public class DirectoryButton extends javax.swing.JPanel {
        
    /**
     * Creates new form FileButton
     */
    public DirectoryButton() {
        initComponents();
    }
    
    public String getLabelText() {
        return jLabelFile.getText();
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "Defines the single line of text for the label.")
    public void setLabelText(String text) {
        jLabelFile.setText(text);
    }
    
    public String getDirectoryPath() {
        return jTextFieldFile.getText();
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "The default text that will appear in the text field.")
    public void setDirectoryPath(String path) {
        jTextFieldFile.setText(path);
    }
    
    public Icon getButtonIcon() {
        return jButtonFile.getIcon();
    }
    
    @BeanProperty(preferred = true, visualUpdate = true, description = "The icon on the file selector button.")
    public void setButtonIcon(Icon icon) {
        jButtonFile.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserFiles = new javax.swing.JFileChooser();
        flatFileViewDirectoryIcon = new com.formdev.flatlaf.icons.FlatFileViewDirectoryIcon();
        jLabelFile = new javax.swing.JLabel();
        jTextFieldFile = new javax.swing.JTextField();
        jButtonFile = new javax.swing.JButton();

        jFileChooserFiles.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setMinimumSize(new java.awt.Dimension(250, 25));
        setPreferredSize(new java.awt.Dimension(400, 25));

        jLabelFile.setText("Path name :");

        jTextFieldFile.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldFile.setText("jTextField1");
        jTextFieldFile.setMinimumSize(new java.awt.Dimension(50, 26));

        jButtonFile.setIcon(flatFileViewDirectoryIcon);
        jButtonFile.setMaximumSize(new java.awt.Dimension(26, 26));
        jButtonFile.setMinimumSize(new java.awt.Dimension(26, 26));
        jButtonFile.setPreferredSize(new java.awt.Dimension(26, 26));
        jButtonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelFile)
                    .addComponent(jTextFieldFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileActionPerformed
        openFileChooser(jTextFieldFile);
    }//GEN-LAST:event_jButtonFileActionPerformed

    protected void openFileChooser(JTextField textField) {
        File file = PathHelpers.getNearestValidParent(Path.of(textField.getText()));
        jFileChooserFiles.setCurrentDirectory(file);
        int returnVal = jFileChooserFiles.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File newFile = jFileChooserFiles.getSelectedFile();
            textField.setText(newFile.getAbsolutePath());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.formdev.flatlaf.icons.FlatFileViewDirectoryIcon flatFileViewDirectoryIcon;
    private javax.swing.JButton jButtonFile;
    private javax.swing.JFileChooser jFileChooserFiles;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JTextField jTextFieldFile;
    // End of variables declaration//GEN-END:variables
}
