/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.core.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.sfc.sf2.application.settings.CoreSettings;
import com.sfc.sf2.application.settings.SettingsManager;
import com.sfc.sf2.helpers.PathHelpers;
import java.io.File;
import java.io.PrintStream;
import java.net.URISyntaxException;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 *
 * @author TiMMy
 */
public class CoreMainEditor extends javax.swing.JFrame {
        
    /**
     * Creates new form New Application
     */
    public CoreMainEditor() {
        initComponents();
        initApp();
        initEditor();
    }
    
    private void initApp() {
        initConsole(jTextAreaConsole);
        initLogger("com.sfc.sf2.graphics", Level.FINEST);
        SettingsManager.loadSettingsFile();
        
        //Check if settings panel should be shown
        if (!SettingsManager.isRunningInEditor()) {
            java.awt.EventQueue.invokeLater(() -> {
                CoreSettings core = SettingsManager.getSettingsStore("core");
                if (!core.arePathsSet()) {
                    jFrameSettings.setVisible(true);
                }
            });
        }
    }
    
    private void initConsole(JTextArea textArea) {
        PrintStream con=new PrintStream(new TextAreaOutputStream(textArea));
        System.setOut(con);
        System.setErr(con);
    }
    
    private void initLogger(String name, Level level) {
        System.setProperty("java.util.logging.SimpleFormatter.format", "%2$s - %5$s%6$s%n");
        Logger log = Logger.getLogger(name);
        log.setUseParentHandlers(false);
        log.setLevel(level);
        ConsoleHandler ch = new ConsoleHandler();
        ch.setLevel(level);        
        log.addHandler(ch);
    }
    
    protected void initEditor() {
        //TODO define a default layout class (or support multiple in the main editor
        //jPanel2.removeAll();
        //jPanel2.setLayout(new GridLayout(1, 1));
        //jPanel2.add(defaultLayout);
    }
    
    protected void updateEditorData() {
        //TODO define a default layout class (or support multiple in the main editor
        //defaultLayout.setTilesPerRow(tileWidth);
        //defaultLayout.setTiles(tiles);
        
        repaintEditorLayout();
    }
    
    protected void repaintEditorLayout() {
        //TODO define a default layout class (or support multiple in the main editor
        //defaultLayout.revalidate();
        //defaultLayout.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameSettings = new javax.swing.JFrame();
        jPanelSettings = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        directoryButtonBasePath = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        directoryButtonIncbinPath = new com.sfc.sf2.core.gui.controls.DirectoryButton();
        jRadioThemeLight = new javax.swing.JRadioButton();
        jRadioThemeDark = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        buttonGroupTheme = new javax.swing.ButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemSettings = new javax.swing.JMenuItem();

        jFrameSettings.setTitle("Settings");
        jFrameSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrameSettings.setLocationByPlatform(true);
        jFrameSettings.setMinimumSize(new java.awt.Dimension(500, 200));
        jFrameSettings.setName("Frame Settings"); // NOI18N
        jFrameSettings.setResizable(false);
        jFrameSettings.setSize(new java.awt.Dimension(500, 250));
        jFrameSettings.setType(java.awt.Window.Type.POPUP);
        jFrameSettings.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrameSettingsWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrameSettingsWindowOpened(evt);
            }
        });

        jPanelSettings.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanelSettings.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel3.setText("Base folder is where the .jar file is expected to be run from");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        directoryButtonBasePath.setLabelText("Base folder :");

        directoryButtonIncbinPath.setLabelText("incbin folder :");

        buttonGroupTheme.add(jRadioThemeLight);
        jRadioThemeLight.setSelected(true);
        jRadioThemeLight.setText("Light");

        buttonGroupTheme.add(jRadioThemeDark);
        jRadioThemeDark.setText("Dark");

        jLabel6.setText("<html>Theme <i>(Requires restart)</i>  :</html>");

        jLabel7.setText("<html>Incbin is the root folder for the disassemby (usually SF2DISASM\\disasm\\)</html>");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setMinimumSize(new java.awt.Dimension(111, 32));

        javax.swing.GroupLayout jPanelSettingsLayout = new javax.swing.GroupLayout(jPanelSettings);
        jPanelSettings.setLayout(jPanelSettingsLayout);
        jPanelSettingsLayout.setHorizontalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directoryButtonBasePath, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(directoryButtonIncbinPath, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jPanelSettingsLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioThemeLight)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioThemeDark)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSettingsLayout.setVerticalGroup(
            jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(directoryButtonBasePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directoryButtonIncbinPath, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jRadioThemeDark)
                    .addComponent(jRadioThemeLight)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrameSettingsLayout = new javax.swing.GroupLayout(jFrameSettings.getContentPane());
        jFrameSettings.getContentPane().setLayout(jFrameSettingsLayout);
        jFrameSettingsLayout.setHorizontalGroup(
            jFrameSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameSettingsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jFrameSettingsLayout.setVerticalGroup(
            jFrameSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameSettingsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2 App");

        jSplitPane1.setDividerLocation(550);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPanel15);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));
        jPanel7.setToolTipText("");

        jTextAreaConsole.setEditable(false);
        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsole);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jSplitPane1.setBottomComponent(jPanel7);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jMenuFile.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuSettings.setText("Settings");

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemSettings);

        jMenuBar1.add(jMenuSettings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        jFrameSettings.setVisible(true);
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jFrameSettingsWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameSettingsWindowClosing
        CoreSettings core = SettingsManager.getSettingsStore("core");
        core.setBasePath(directoryButtonBasePath.getDirectoryPath());
        core.setIncbinPath(directoryButtonIncbinPath.getDirectoryPath());
        core.setIsDarkTheme(jRadioThemeDark.isSelected());
        SettingsManager.saveSettingsFile();
    }//GEN-LAST:event_jFrameSettingsWindowClosing

    private void jFrameSettingsWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameSettingsWindowOpened
        jFrameSettings.setLocationRelativeTo(this);
        jFrameSettings.setSize(jFrameSettings.getPreferredSize());
        CoreSettings core = SettingsManager.getSettingsStore("core");
        if (core.arePathsSet()) {
            directoryButtonBasePath.setDirectoryPath(core.getBasePath());
            directoryButtonIncbinPath.setDirectoryPath(core.getIncbinPath());
            jRadioThemeLight.setSelected(!core.getIsDarkTheme());
            jRadioThemeDark.setSelected(core.getIsDarkTheme());
        } else {
            directoryButtonBasePath.setDirectoryPath(PathHelpers.getApplicationpath().toString());
            directoryButtonIncbinPath.setDirectoryPath(PathHelpers.getApplicationpath().toString());
        }
    }//GEN-LAST:event_jFrameSettingsWindowOpened
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        CoreMainEditor.programSetup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoreMainEditor().setVisible(true);
            }
        });
    }
    
    public static void programSetup() {
        //Hack to determine if project is running from editor (IDE) or is a build. (property 'user.dir' is blank if in editor)
        String dir = System.getProperty("user.dir");
        SettingsManager.setRunningInEditor(dir == null || dir.length() == 0);
        
        //Core setup
        try {
            File workingDirectory = new File(CoreMainEditor.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile();
            System.setProperty("user.dir", workingDirectory.toString());
        } catch (URISyntaxException ex) {
            System.getLogger(CoreMainEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        SettingsManager.loadSettingsFile();
        
        //Set look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //Have to load core settings first to check theme                                     
            CoreSettings core = SettingsManager.getSettingsStore("core");
            if (core.getIsDarkTheme())
                FlatDarkLaf.setup();
            else
                FlatLightLaf.setup();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CoreMainEditor.class.getName()).log(java.util.logging.Level.SEVERE, "FlatLaf theme could not be loaded. Loading default theme instead", ex);
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex1) {
                java.util.logging.Logger.getLogger(CoreMainEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold>
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTheme;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonBasePath;
    private com.sfc.sf2.core.gui.controls.DirectoryButton directoryButtonIncbinPath;
    private javax.swing.JFrame jFrameSettings;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JRadioButton jRadioThemeDark;
    private javax.swing.JRadioButton jRadioThemeLight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaConsole;
    // End of variables declaration//GEN-END:variables

}
