/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sfc.sf2.core.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.sfc.sf2.application.settings.CoreSettings;
import com.sfc.sf2.application.settings.SettingsManager;
import com.sfc.sf2.helpers.PathHelpers;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.PrintStream;
import java.net.URISyntaxException;
import java.nio.file.Path;
import java.util.logging.ConsoleHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author wiz
 */
public class MainEditor extends javax.swing.JFrame {
    
    /**
     * Creates new form New Application
     */
    public MainEditor() {
        initComponents();
        initApp();
        initEditor();
    }
    
    protected void initApp() {
        initConsole(jTextAreaConsole);
        System.setProperty("java.util.logging.SimpleFormatter.format", "%2$s - %5$s%6$s%n");
        initLogger("com.sfc.sf2.graphics", Level.FINEST);
        try {
            File workingDirectory = new File(MainEditor.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile();
            System.setProperty("user.dir", workingDirectory.toString());
        } catch (URISyntaxException ex) {
            System.getLogger(MainEditor.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        SettingsManager.loadSettingsFile();
        
        //Check if settings panel should be shown
        Timer timer = new Timer(250, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CoreSettings core = SettingsManager.getSettingsStore("core");
                if (!core.arePathsSet()) {
                    jTextFieldBaseFolder.setText(PathHelpers.getApplicationpath().toString());
                    jTextFieldIncbinFolder.setText(PathHelpers.getApplicationpath().toString());
                    jFrameSettings.setVisible(true);
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    private static void initConsole(JTextArea textArea){
        PrintStream con=new PrintStream(new TextAreaOutputStream(textArea));
        System.setOut(con);
        System.setErr(con);
    }
    
    private void initLogger(String name, Level level){
        Logger log = Logger.getLogger(name);
        log.setUseParentHandlers(false);
        log.setLevel(level);
        ConsoleHandler ch = new ConsoleHandler();
        ch.setLevel(level);        
        log.addHandler(ch);
    }
    
    protected void openFileChooser(JTextField textField) {
        jFileChooserFiles.setCurrentDirectory(Path.of(textField.getText()).toFile());
        int returnVal = jFileChooserFiles.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserFiles.getSelectedFile();
            textField.setText(file.getAbsolutePath());
        }
    }
    
    protected void openDirectoryChooser(JTextField textField) {
        jFileChooserDirectories.setCurrentDirectory(Path.of(textField.getText()).toFile());
        int returnVal = jFileChooserDirectories.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jFileChooserDirectories.getSelectedFile();
            textField.setText(file.getAbsolutePath());
        }
    }
    
    protected void initEditor() {
        //TODO define a default layout class (or support multiple in the main editor
        //jPanel2.removeAll();
        //jPanel2.setLayout(new GridLayout(1, 1));
        //jPanel2.add(defaultLayout);
    }
    
    protected void updateEditorData() {
        //TODO define a default layout class (or support multiple in the main editor
        //defaultLayout.setTilesPerRow(tileWidth);
        //defaultLayout.setTiles(tiles);
    }
    
    protected void repaintEditorLayout() {
        //TODO define a default layout class (or support multiple in the main editor
        //defaultLayout.revalidate();
        //defaultLayout.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserFiles = new javax.swing.JFileChooser();
        jFileChooserDirectories = new javax.swing.JFileChooser();
        jColorChooser1 = new javax.swing.JColorChooser();
        jFrameSettings = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButtonBaseFolder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIncbinFolder = new javax.swing.JTextField();
        jTextFieldBaseFolder = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonIncbinFolder = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        flatSearchIcon1 = new com.formdev.flatlaf.icons.FlatSearchIcon();
        flatFileViewFileIcon1 = new com.formdev.flatlaf.icons.FlatFileViewFileIcon();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemSettings = new javax.swing.JMenuItem();

        jFileChooserDirectories.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        jFrameSettings.setTitle("Settings");
        jFrameSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrameSettings.setLocationByPlatform(true);
        jFrameSettings.setMinimumSize(new java.awt.Dimension(500, 200));
        jFrameSettings.setName("Frame Settings"); // NOI18N
        jFrameSettings.setPreferredSize(new java.awt.Dimension(500, 250));
        jFrameSettings.setResizable(false);
        jFrameSettings.setSize(new java.awt.Dimension(500, 250));
        jFrameSettings.setType(java.awt.Window.Type.POPUP);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));

        jButtonBaseFolder.setIcon(flatFileViewFileIcon1);
        jButtonBaseFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaseFolderActionPerformed(evt);
            }
        });

        jLabel2.setText("Incbin folder :");

        jTextFieldIncbinFolder.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldIncbinFolder.setText("jTextField1");

        jTextFieldBaseFolder.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextFieldBaseFolder.setText("jTextField1");

        jLabel1.setText("Base folder :");

        jButtonIncbinFolder.setIcon(flatFileViewFileIcon1);
        jButtonIncbinFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncbinFolderActionPerformed(evt);
            }
        });

        jLabel3.setText("Base folder is where the .jar file is expected to be run from");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setText("<html>Incbin is the root folder for the disassemby (usually SF2DISASM\\disasm\\)</html>");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setMinimumSize(new java.awt.Dimension(111, 32));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIncbinFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBaseFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBaseFolder)
                            .addComponent(jButtonIncbinFolder)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldBaseFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBaseFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonIncbinFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIncbinFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jFrameSettingsLayout = new javax.swing.GroupLayout(jFrameSettings.getContentPane());
        jFrameSettings.getContentPane().setLayout(jFrameSettingsLayout);
        jFrameSettingsLayout.setHorizontalGroup(
            jFrameSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameSettingsLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jFrameSettingsLayout.setVerticalGroup(
            jFrameSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameSettingsLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SF2 App");

        jSplitPane1.setDividerLocation(550);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jSplitPane1.setTopComponent(jPanel15);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));
        jPanel7.setToolTipText("");

        jTextAreaConsole.setEditable(false);
        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsole);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jSplitPane1.setBottomComponent(jPanel7);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jMenuFile.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuSettings.setText("Settings");

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemSettings);

        jMenuBar1.add(jMenuSettings);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 664));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        CoreSettings core = SettingsManager.getSettingsStore("core");
        jTextFieldBaseFolder.setText(core.getBasePath());
        jTextFieldIncbinFolder.setText(core.getIncbinPath());
        jFrameSettings.setVisible(true);
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jButtonIncbinFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncbinFolderActionPerformed
        openDirectoryChooser(jTextFieldIncbinFolder);
    }//GEN-LAST:event_jButtonIncbinFolderActionPerformed

    private void jButtonBaseFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaseFolderActionPerformed
        openDirectoryChooser(jTextFieldBaseFolder);
    }//GEN-LAST:event_jButtonBaseFolderActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            FlatDarkLaf.setup();
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex1) {
                java.util.logging.Logger.getLogger(MainEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.formdev.flatlaf.icons.FlatFileViewFileIcon flatFileViewFileIcon1;
    private com.formdev.flatlaf.icons.FlatSearchIcon flatSearchIcon1;
    private javax.swing.JButton jButtonBaseFolder;
    private javax.swing.JButton jButtonIncbinFolder;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFileChooser jFileChooserDirectories;
    private javax.swing.JFileChooser jFileChooserFiles;
    private javax.swing.JFrame jFrameSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.JTextField jTextFieldBaseFolder;
    private javax.swing.JTextField jTextFieldIncbinFolder;
    // End of variables declaration//GEN-END:variables

}
