/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
 */
package com.sfc.sf2.palette.gui;

import com.sfc.sf2.palette.PaletteDecoder;
import java.awt.Color;
import javax.swing.JSlider;

/**
 *
 * @author TiMMy
 */
public class ColorEditor extends javax.swing.JPanel {

    ColorPane colorPane;
    Color color;
    int redIndex, greenIndex, blueIndex;
    
    public ColorEditor() {
        initComponents();
        jLabelRGB.setText("");
    }
    
    private void updateColor() {
        int r = PaletteDecoder.cramIndexToBrightness(redIndex);
        int g = PaletteDecoder.cramIndexToBrightness(greenIndex);
        int b = PaletteDecoder.cramIndexToBrightness(blueIndex);
        color = new Color(r, g, b);
        jPanelColor.setBackground(color);
        colorPane.updateColor(color);
        displayRGBColor();
        jPanelColor.revalidate();
    }
  
    public void setColorPane(ColorPane cp){
        colorPane = cp;
        Color color = colorPane.getCurrentColor();
        redIndex = PaletteDecoder.brightnessToCramIndex(color.getRed());
        greenIndex = PaletteDecoder.brightnessToCramIndex(color.getGreen());
        blueIndex = PaletteDecoder.brightnessToCramIndex(color.getBlue());
        sliderR.setValue(redIndex);
        sliderG.setValue(greenIndex);
        sliderB.setValue(blueIndex);
        updateColor();
    }

    public void displayRGBColor() {
        int r = PaletteDecoder.cramIndexToBrightness(redIndex);
        int g = PaletteDecoder.cramIndexToBrightness(greenIndex);
        int b = PaletteDecoder.cramIndexToBrightness(blueIndex);
        jLabelRGB.setText(String.format("# R: %2d, G: %2d, B: %2d", r, g, b));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderR = new javax.swing.JSlider();
        sliderG = new javax.swing.JSlider();
        sliderB = new javax.swing.JSlider();
        jPanelColor = new javax.swing.JPanel();
        jLabelRGB = new javax.swing.JLabel();

        sliderR.setMajorTickSpacing(2);
        sliderR.setMaximum(14);
        sliderR.setMinorTickSpacing(2);
        sliderR.setPaintLabels(true);
        sliderR.setPaintTicks(true);
        sliderR.setSnapToTicks(true);
        sliderR.setValue(0);
        sliderR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        sliderG.setMajorTickSpacing(2);
        sliderG.setMaximum(14);
        sliderG.setMinorTickSpacing(2);
        sliderG.setPaintLabels(true);
        sliderG.setPaintTicks(true);
        sliderG.setSnapToTicks(true);
        sliderG.setValue(0);
        sliderG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        sliderB.setMajorTickSpacing(2);
        sliderB.setMaximum(14);
        sliderB.setMinorTickSpacing(2);
        sliderB.setPaintLabels(true);
        sliderB.setPaintTicks(true);
        sliderB.setSnapToTicks(true);
        sliderB.setValue(0);
        sliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        jPanelColor.setBackground(new java.awt.Color(0, 0, 0));
        jPanelColor.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelRGB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRGB.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRGB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderB, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderG, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sliderR, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRGB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        JSlider slider = (JSlider)evt.getSource();
        if (slider == sliderR) redIndex = sliderR.getValue();
        if (slider == sliderG) greenIndex = sliderG.getValue();
        if (slider == sliderB) blueIndex = sliderB.getValue();
        updateColor();
    }//GEN-LAST:event_sliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelRGB;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JSlider sliderB;
    private javax.swing.JSlider sliderG;
    private javax.swing.JSlider sliderR;
    // End of variables declaration//GEN-END:variables
}
