name: Dependency-Aware Build

on:
  push:
    branches: [main]
    paths:
      - '**/version.properties'
  pull_request:
    branches: [main]
    paths:
      - '**/version.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Detect changed projects and resolve dependencies
        id: project-graph
        shell: bash
        run: |
          git fetch origin ${{ github.event.before }}
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'version.properties' || true)

          echo "Changed files:"
          echo "$changed_files"

          changed_projects=()
          for file in $changed_files; do
            project=$(dirname "$file")
            changed_projects+=("$(basename "$project")")
          done

          echo "Changed projects: ${changed_projects[@]}"

          declare -A dependencies

          # Parse project.properties only for changed projects (recursively resolve)
          # To resolve dependencies of dependencies, define a function:

          parse_deps() {
            local proj="$1"
            # Avoid re-parsing
            if [[ -n "${dependencies[$proj]+x}" ]]; then
              return
            fi

            local props_file="${proj}/nbproject/project.properties"
            local deps=""
            if [ -f "$props_file" ]; then
              while IFS= read -r line; do
                if [[ "$line" =~ ^project\..*=.*$ ]]; then
                  ref_path=$(echo "$line" | cut -d'=' -f2 | xargs)
                  ref_name=$(basename "$ref_path")
                  deps="$deps $ref_name"
                fi
              done < "$props_file"
              deps=$(echo "$deps" | xargs) # trim whitespace
              dependencies["$proj"]="$deps"
              # Recursively parse dependencies
              for d in $deps; do
                parse_deps "$d"
              done
            else
              echo "Warning: $props_file not found"
              dependencies["$proj"]=""
            fi
          }

          for proj in "${changed_projects[@]}"; do
            parse_deps "$proj"
          done

          echo "Discovered dependencies:"
          for proj in "${!dependencies[@]}"; do
            echo "  $proj -> ${dependencies[$proj]}"
          done

          build_set=()
          visited=()

          resolve_deps() {
            local proj="$1"
            if [[ " ${visited[@]} " =~ " ${proj} " ]]; then return; fi
            visited+=("$proj")
            for dep in ${dependencies[$proj]}; do
              resolve_deps "$dep"
            done
            build_set+=("$proj")
          }

          for proj in "${changed_projects[@]}"; do
            resolve_deps "$proj"
          done

          echo "Build order:"
          for proj in "${build_set[@]}"; do
            echo "$proj"
          done

          echo "BUILD_ORDER<<EOF" >> $GITHUB_ENV
          for proj in "${build_set[@]}"; do
            echo "$proj"
          done
          echo "EOF" >> $GITHUB_ENV

      - name: Build projects in dependency order
        run: |
          echo "Building projects in order:"
          mkdir -p built-jars
          
          for proj in $BUILD_ORDER; do
            echo "Building $proj..."

            mkdir -p "$proj/build/classes"
            mkdir -p "$proj/dist"
            mkdir -p "$proj/lib"

            # Copy dependencies' jars into this project's lib/
            for dep in $BUILD_ORDER; do
              if [ "$dep" == "$proj" ]; then break; fi
              if [ -f "built-jars/$dep.jar" ]; then
                echo "  Adding $dep.jar to $proj/lib/"
                cp "built-jars/$dep.jar" "$proj/lib/"
              fi
            done

            # Build using Ant
            ant -f "$proj" -Dnb.internal.action.name=rebuild -Dplatforms.JDK_17.home="$JAVA_HOME" clean jar
            
            # Move built jar to shared location
            jar_name=$(basename "$proj")
            if [ -f "$proj/dist/${jar_name}.jar" ]; then
              cp "$proj/dist/${jar_name}.jar" "built-jars/$jar_name.jar"
            else
              echo "Warning: $proj/dist/${jar_name}.jar not found"
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: '**/dist/*.jar'
