name: Build Changed Projects

on:
  push:
    branches:
      - main
    paths:
      - '**/version.properties'
  pull_request:
    branches:
      - main
    paths:
      - '**/version.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Get changed version.properties files
        id: changed-files
        run: |
          git fetch origin ${{ github.event.before }}
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'version.properties' || true)
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$changed_files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build each changed project with Ant
        run: |
          echo "JAVA_HOME is $JAVA_HOME"
          mkdir -p built-jars
          for file in $CHANGED_FILES; do
            project_dir=$(dirname "$file")
            echo "Building project in $project_dir with Ant"
            ant -f "$project_dir" -Dnb.internal.action.name=rebuild -Dplatforms.JDK_17.home="$JAVA_HOME" clean jar
            # Copy generated jars to a common folder for upload
            if [ -d "$project_dir/dist" ]; then
              cp "$project_dir"/dist/*.jar built-jars/ || true
            fi
          done

      - name: Upload built jars
        uses: actions/upload-artifact@v3
        with:
          name: built-jars
          path: built-jars/*.jar
