name: Dependency-Aware Build

on:
  push:
    branches: [main]
    paths:
      - '**/version.properties'
  pull_request:
    branches: [main]
    paths:
      - '**/version.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Detect changed projects and resolve dependencies
        id: project-graph
        shell: bash
        run: |
          git fetch origin ${{ github.event.before }}

          # Find changed version.properties files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'version.properties' || true)

          echo "Changed files:"
          echo "$changed_files"

          changed_projects=()
          for file in $changed_files; do
            project=$(dirname "$file")
            changed_projects+=("$(basename "$project")")
          done

          echo "Changed projects: ${changed_projects[@]}"

          # Export changed projects to environment
          echo "CHANGED_PROJECTS=${changed_projects[*]}" >> $GITHUB_ENV

          declare -A dependencies

          # Parse project.properties for changed projects and recursively for dependencies
          parse_deps() {
            local proj="$1"
            # Avoid re-parsing
            if [[ -n "${dependencies[$proj]+x}" ]]; then
              return
            fi

            local props_file="${proj}/nbproject/project.properties"
            local deps=""
            if [ -f "$props_file" ]; then
              while IFS= read -r line; do
                if [[ "$line" =~ ^project\..*=.*$ ]]; then
                  ref_path=$(echo "$line" | cut -d'=' -f2 | xargs)
                  ref_name=$(basename "$ref_path")
                  deps="$deps $ref_name"
                fi
              done < "$props_file"
              deps=$(echo "$deps" | xargs) # trim whitespace
              dependencies["$proj"]="$deps"
              # Recursively parse dependencies
              for d in $deps; do
                parse_deps "$d"
              done
            else
              echo "Warning: $props_file not found"
              dependencies["$proj"]=""
            fi
          }

          for proj in "${changed_projects[@]}"; do
            parse_deps "$proj"
          done

          echo "Discovered dependencies:"
          for proj in "${!dependencies[@]}"; do
            echo "  $proj -> ${dependencies[$proj]}"
          done

          build_set=()
          visited=()

          resolve_deps() {
            local proj="$1"
            if [[ " ${visited[@]} " =~ " ${proj} " ]]; then return; fi
            visited+=("$proj")
            for dep in ${dependencies[$proj]}; do
              resolve_deps "$dep"
            done
            build_set+=("$proj")
          }

          for proj in "${changed_projects[@]}"; do
            resolve_deps "$proj"
          done

          echo "Build order:"
          for proj in "${build_set[@]}"; do
            echo "$proj"
          done

          # Export build order (space separated) for next step
          echo "BUILD_ORDER=${build_set[*]}" >> $GITHUB_ENV

      - name: Build dependencies and changed projects separately
        shell: bash
        run: |
          echo "Starting build process..."

          mkdir -p built-jars

          read -a BUILD_ORDER <<< "$BUILD_ORDER"
          read -a CHANGED_PROJECTS <<< "$CHANGED_PROJECTS"

          # Convert CHANGED_PROJECTS array to lookup for quick check
          declare -A changed_map
          for p in "${CHANGED_PROJECTS[@]}"; do
            changed_map["$p"]=1
          done

          # Pahse 1: Build dependencies
          echo "Phase 1: Build dependencies (non-changed projects)"
          for proj in "${BUILD_ORDER[@]}"; do
            if [[ -z "${changed_map[$proj]}" ]]; then
              echo "Building dependency $proj with target 'jar'..."

              mkdir -p "$proj/build/classes"
              mkdir -p "$proj/dist/lib"
              mkdir -p "$proj/lib"

              ant -q -f "$proj/build.xml" -Dnb.internal.action.name=rebuild -Dplatforms.JDK_17.home="$JAVA_HOME" clean jar

              jar_name=$(basename "$proj")
              if [ -f "$proj/dist/${jar_name}.jar" ]; then
              
              else
                echo "Warning: $proj/dist/${jar_name}.jar not found after build"
              fi
            fi
          done
          
          # Pahse 2: Build changed apps
          echo "Phase 2: Build changed projects with 'package-for-store' and inject dependencies"
          for proj in "${BUILD_ORDER[@]}"; do
            if [[ -n "${changed_map[$proj]}" ]]; then
              echo "Building changed project $proj with target 'package-for-store'..."

              mkdir -p "$proj/build/classes"
              mkdir -p "$proj/dist/lib"
              mkdir -p "$proj/lib"

              # Copy dependencies jars into dist/lib/
              for dep in "${BUILD_ORDER[@]}"; do
                if [[ "$dep" == "$proj" ]]; then
                  break
                fi
                if [ -f "$dep/dist/$dep.jar" ]; then
                  echo "  Copying dependency $dep.jar into $proj/dist/lib/"
                  cp "$dep/dist/$dep.jar" "$proj/dist/lib/"
                  cp "$dep/dist/lib/*.jar" "$proj/dist/lib/"
                fi
              done

              echo "Contents of $proj/dist/lib/ before build:"
              ls -la "$proj/dist/lib"

              ant -q -f "$proj/build.xml" -Dnb.internal.action.name=rebuild -Dplatforms.JDK_17.home="$JAVA_HOME" clean package-for-store

              jar_name=$(basename "$proj")
              if [ -f "$proj/dist/${jar_name}.jar" ]; then
                cp "$proj/dist/${jar_name}.jar" "built-jars/$jar_name.jar"
              else
                echo "Warning: $proj/dist/${jar_name}.jar not found after package-for-store"
              fi
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: built-jars/*.jar
