name: Dependency-Aware Build

on:
  push:
    branches: [main]
    paths:
      - '**/version.properties'
  pull_request:
    branches: [main]
    paths:
      - '**/version.properties'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Detect changed projects and resolve dependencies
        id: project-graph
        run: |
          git fetch origin ${{ github.event.before }}
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'version.properties' || true)

          echo "Changed files:"
          echo "$changed_files"

          # Extract changed projects
          changed_projects=()
          for file in $changed_files; do
            project=$(dirname "$file")
            changed_projects+=("$(basename "$project")")
          done

          echo "Changed projects: ${changed_projects[@]}"

          # Discover dependencies from NetBeans-style project.properties
          declare -A dependencies

          for dir in */ ; do
            project_name=$(basename "$dir")
            props_file="${dir}nbproject/project.properties"
            deps=""
            if [ -f "$props_file" ]; then
              while IFS= read -r line; do
                if [[ "$line" == project.*=* ]]; then
                  ref_path=$(echo "$line" | cut -d'=' -f2 | xargs)
                  ref_name=$(b_
